### ISSUE TITLE
MiniMagick error when creating a work.

### ISSUE THREAD

**Issue by spikewilliams** [osulibraries/hydra-docker-demo#1]
When I created the first New Work on a fresh install of the Docker image, an error was thrown in the CurationConcerns::WorksController. 

Here is the stacktrace:

MiniMagick::Invalid in CurationConcerns::WorksController#create
`identify /tmp/mini_magick20161016-1-yqsk20.pdf` failed with error:

Extracted source (around line #204):
202     identify
203   rescue MiniMagick::Error => error
204     raise MiniMagick::Invalid, error.message
205   end
206
207   ##

Rails.root: /hydra-docker-demo

Application Trace | Framework Trace | Full Trace
mini_magick (4.5.1) lib/mini_magick/image.rb:204:in `rescue in validate!'
mini_magick (4.5.1) lib/mini_magick/image.rb:202:in`validate!'
mini_magick (4.5.1) lib/mini_magick/image.rb:113:in `block in create'
mini_magick (4.5.1) lib/mini_magick/image.rb:112:in`tap'
mini_magick (4.5.1) lib/mini_magick/image.rb:112:in `create'
mini_magick (4.5.1) lib/mini_magick/image.rb:34:in`read'
mini_magick (4.5.1) lib/mini_magick/image.rb:90:in `block in open'
/usr/local/lib/ruby/2.3.0/open-uri.rb:37:in`open'
/usr/local/lib/ruby/2.3.0/open-uri.rb:37:in `open'
mini_magick (4.5.1) lib/mini_magick/image.rb:89:in`open'
hydra-derivatives (3.1.1) lib/hydra/derivatives/processors/image.rb:55:in `load_image_transformer'
hydra-derivatives (3.1.1) lib/hydra/derivatives/processors/image.rb:37:in`create_image'
hydra-derivatives (3.1.1) lib/hydra/derivatives/processors/image.rb:31:in `create_resized_image'
hydra-derivatives (3.1.1) lib/hydra/derivatives/processors/image.rb:25:in`process_without_timeout'
hydra-derivatives (3.1.1) lib/hydra/derivatives/processors/image.rb:8:in `process'
hydra-derivatives (3.1.1) lib/hydra/derivatives/runners/runner.rb:32:in`block (2 levels) in create'
hydra-derivatives (3.1.1) lib/hydra/derivatives/runners/runner.rb:29:in `each'
hydra-derivatives (3.1.1) lib/hydra/derivatives/runners/runner.rb:29:in`block in create'
curation_concerns (1.3.0) app/services/curation_concerns/local_file_service.rb:7:in `call'
hydra-derivatives (3.1.1) lib/hydra/derivatives/runners/runner.rb:43:in`source_file'
hydra-derivatives (3.1.1) lib/hydra/derivatives/runners/runner.rb:28:in `create'
curation_concerns (1.3.0) app/models/concerns/curation_concerns/file_set/derivatives.rb:19:in`create_derivatives'
curation_concerns (1.3.0) app/jobs/create_derivatives_job.rb:10:in `perform'
activejob (4.2.6) lib/active_job/execution.rb:32:in`block in perform_now'
activesupport (4.2.6) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.6) lib/active_support/callbacks.rb:555:in`block (2 levels) in compile'
activesupport (4.2.6) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.6) lib/active_support/callbacks.rb:498:in`block (2 levels) in around'
activesupport (4.2.6) lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
i18n (0.7.0) lib/i18n.rb:257:in`with_locale'
activejob (4.2.6) lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
activesupport (4.2.6) lib/active_support/callbacks.rb:441:in`instance_exec'
activesupport (4.2.6) lib/active_support/callbacks.rb:441:in `block in make_lambda'
activesupport (4.2.6) lib/active_support/callbacks.rb:342:in`block in simple'
activesupport (4.2.6) lib/active_support/callbacks.rb:497:in `block in around'
activesupport (4.2.6) lib/active_support/callbacks.rb:505:in`call'
activesupport (4.2.6) lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
activesupport (4.2.6) lib/active_support/callbacks.rb:343:in`block (2 levels) in simple'
activejob (4.2.6) lib/active_job/logging.rb:23:in `block (4 levels) in <module:Logging>'
activesupport (4.2.6) lib/active_support/notifications.rb:164:in`block in instrument'
activesupport (4.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.6) lib/active_support/notifications.rb:164:in`instrument'
activejob (4.2.6) lib/active_job/logging.rb:22:in `block (3 levels) in <module:Logging>'
activejob (4.2.6) lib/active_job/logging.rb:43:in`block in tag_logger'
activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.6) lib/active_support/tagged_logging.rb:26:in`tagged'
activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `tagged'
activejob (4.2.6) lib/active_job/logging.rb:43:in`tag_logger'
activejob (4.2.6) lib/active_job/logging.rb:19:in `block (2 levels) in <module:Logging>'
activesupport (4.2.6) lib/active_support/callbacks.rb:441:in`instance_exec'
activesupport (4.2.6) lib/active_support/callbacks.rb:441:in `block in make_lambda'
activesupport (4.2.6) lib/active_support/callbacks.rb:342:in`block in simple'
activesupport (4.2.6) lib/active_support/callbacks.rb:497:in `block in around'
activesupport (4.2.6) lib/active_support/callbacks.rb:505:in`call'
activesupport (4.2.6) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
activesupport (4.2.6) lib/active_support/callbacks.rb:778:in`_run_perform_callbacks'
activesupport (4.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
activejob (4.2.6) lib/active_job/execution.rb:31:in`perform_now'
activejob (4.2.6) lib/active_job/execution.rb:21:in `execute'
activejob (4.2.6) lib/active_job/queue_adapters/inline_adapter.rb:14:in`enqueue'
activejob (4.2.6) lib/active_job/enqueuing.rb:71:in `block in enqueue'
activesupport (4.2.6) lib/active_support/callbacks.rb:117:in`call'
activesupport (4.2.6) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
activesupport (4.2.6) lib/active_support/callbacks.rb:505:in`call'
activesupport (4.2.6) lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
activesupport (4.2.6) lib/active_support/callbacks.rb:343:in`block (2 levels) in simple'
activejob (4.2.6) lib/active_job/logging.rb:14:in `block (3 levels) in <module:Logging>'
activejob (4.2.6) lib/active_job/logging.rb:43:in`block in tag_logger'
activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.6) lib/active_support/tagged_logging.rb:26:in`tagged'
activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `tagged'
activejob (4.2.6) lib/active_job/logging.rb:43:in`tag_logger'
activejob (4.2.6) lib/active_job/logging.rb:13:in `block (2 levels) in <module:Logging>'
activesupport (4.2.6) lib/active_support/callbacks.rb:441:in`instance_exec'
activesupport (4.2.6) lib/active_support/callbacks.rb:441:in `block in make_lambda'
activesupport (4.2.6) lib/active_support/callbacks.rb:342:in`block in simple'
activesupport (4.2.6) lib/active_support/callbacks.rb:497:in `block in around'
activesupport (4.2.6) lib/active_support/callbacks.rb:505:in`call'
activesupport (4.2.6) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_enqueue_callbacks'
activesupport (4.2.6) lib/active_support/callbacks.rb:81:in`run_callbacks'
activejob (4.2.6) lib/active_job/enqueuing.rb:67:in `enqueue'
activejob (4.2.6) lib/active_job/enqueuing.rb:17:in`perform_later'
curation_concerns (1.3.0) app/jobs/characterize_job.rb:13:in `perform'
activejob (4.2.6) lib/active_job/execution.rb:32:in`block in perform_now'
activesupport (4.2.6) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.6) lib/active_support/callbacks.rb:555:in`block (2 levels) in compile'
activesupport (4.2.6) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.6) lib/active_support/callbacks.rb:498:in`block (2 levels) in around'
activesupport (4.2.6) lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
i18n (0.7.0) lib/i18n.rb:257:in`with_locale'
activejob (4.2.6) lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
activesupport (4.2.6) lib/active_support/callbacks.rb:441:in`instance_exec'
activesupport (4.2.6) lib/active_support/callbacks.rb:441:in `block in make_lambda'
activesupport (4.2.6) lib/active_support/callbacks.rb:342:in`block in simple'
activesupport (4.2.6) lib/active_support/callbacks.rb:497:in `block in around'
activesupport (4.2.6) lib/active_support/callbacks.rb:505:in`call'
activesupport (4.2.6) lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
activesupport (4.2.6) lib/active_support/callbacks.rb:343:in`block (2 levels) in simple'
activejob (4.2.6) lib/active_job/logging.rb:23:in `block (4 levels) in <module:Logging>'
activesupport (4.2.6) lib/active_support/notifications.rb:164:in`block in instrument'
activesupport (4.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.6) lib/active_support/notifications.rb:164:in`instrument'
activejob (4.2.6) lib/active_job/logging.rb:22:in `block (3 levels) in <module:Logging>'
activejob (4.2.6) lib/active_job/logging.rb:43:in`block in tag_logger'
activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.6) lib/active_support/tagged_logging.rb:26:in`tagged'
activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `tagged'
activejob (4.2.6) lib/active_job/logging.rb:43:in`tag_logger'
activejob (4.2.6) lib/active_job/logging.rb:19:in `block (2 levels) in <module:Logging>'
activesupport (4.2.6) lib/active_support/callbacks.rb:441:in`instance_exec'
activesupport (4.2.6) lib/active_support/callbacks.rb:441:in `block in make_lambda'
activesupport (4.2.6) lib/active_support/callbacks.rb:342:in`block in simple'
activesupport (4.2.6) lib/active_support/callbacks.rb:497:in `block in around'
activesupport (4.2.6) lib/active_support/callbacks.rb:505:in`call'
activesupport (4.2.6) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
activesupport (4.2.6) lib/active_support/callbacks.rb:778:in`_run_perform_callbacks'
activesupport (4.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
activejob (4.2.6) lib/active_job/execution.rb:31:in`perform_now'
activejob (4.2.6) lib/active_job/execution.rb:21:in `execute'
activejob (4.2.6) lib/active_job/queue_adapters/inline_adapter.rb:14:in`enqueue'
activejob (4.2.6) lib/active_job/enqueuing.rb:71:in `block in enqueue'
activesupport (4.2.6) lib/active_support/callbacks.rb:117:in`call'
activesupport (4.2.6) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
activesupport (4.2.6) lib/active_support/callbacks.rb:505:in`call'
activesupport (4.2.6) lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
activesupport (4.2.6) lib/active_support/callbacks.rb:343:in`block (2 levels) in simple'
activejob (4.2.6) lib/active_job/logging.rb:14:in `block (3 levels) in <module:Logging>'
activejob (4.2.6) lib/active_job/logging.rb:43:in`block in tag_logger'
activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.6) lib/active_support/tagged_logging.rb:26:in`tagged'
activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `tagged'
activejob (4.2.6) lib/active_job/logging.rb:43:in`tag_logger'
activejob (4.2.6) lib/active_job/logging.rb:13:in `block (2 levels) in <module:Logging>'
activesupport (4.2.6) lib/active_support/callbacks.rb:441:in`instance_exec'
activesupport (4.2.6) lib/active_support/callbacks.rb:441:in `block in make_lambda'
activesupport (4.2.6) lib/active_support/callbacks.rb:342:in`block in simple'
activesupport (4.2.6) lib/active_support/callbacks.rb:497:in `block in around'
activesupport (4.2.6) lib/active_support/callbacks.rb:505:in`call'
activesupport (4.2.6) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_enqueue_callbacks'
activesupport (4.2.6) lib/active_support/callbacks.rb:81:in`run_callbacks'
activejob (4.2.6) lib/active_job/enqueuing.rb:67:in `enqueue'
activejob (4.2.6) lib/active_job/enqueuing.rb:17:in`perform_later'
curation_concerns (1.3.0) app/jobs/ingest_file_job.rb:35:in `perform'
activejob (4.2.6) lib/active_job/execution.rb:32:in`block in perform_now'
activesupport (4.2.6) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.6) lib/active_support/callbacks.rb:555:in`block (2 levels) in compile'
activesupport (4.2.6) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.6) lib/active_support/callbacks.rb:498:in`block (2 levels) in around'
activesupport (4.2.6) lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
i18n (0.7.0) lib/i18n.rb:257:in`with_locale'
activejob (4.2.6) lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
activesupport (4.2.6) lib/active_support/callbacks.rb:441:in`instance_exec'
activesupport (4.2.6) lib/active_support/callbacks.rb:441:in `block in make_lambda'
activesupport (4.2.6) lib/active_support/callbacks.rb:342:in`block in simple'
activesupport (4.2.6) lib/active_support/callbacks.rb:497:in `block in around'
activesupport (4.2.6) lib/active_support/callbacks.rb:505:in`call'
activesupport (4.2.6) lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
activesupport (4.2.6) lib/active_support/callbacks.rb:343:in`block (2 levels) in simple'
activejob (4.2.6) lib/active_job/logging.rb:23:in `block (4 levels) in <module:Logging>'
activesupport (4.2.6) lib/active_support/notifications.rb:164:in`block in instrument'
activesupport (4.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.6) lib/active_support/notifications.rb:164:in`instrument'
activejob (4.2.6) lib/active_job/logging.rb:22:in `block (3 levels) in <module:Logging>'
activejob (4.2.6) lib/active_job/logging.rb:43:in`block in tag_logger'
activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.6) lib/active_support/tagged_logging.rb:26:in`tagged'
activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `tagged'
activejob (4.2.6) lib/active_job/logging.rb:43:in`tag_logger'
activejob (4.2.6) lib/active_job/logging.rb:19:in `block (2 levels) in <module:Logging>'
activesupport (4.2.6) lib/active_support/callbacks.rb:441:in`instance_exec'
activesupport (4.2.6) lib/active_support/callbacks.rb:441:in `block in make_lambda'
activesupport (4.2.6) lib/active_support/callbacks.rb:342:in`block in simple'
activesupport (4.2.6) lib/active_support/callbacks.rb:497:in `block in around'
activesupport (4.2.6) lib/active_support/callbacks.rb:505:in`call'
activesupport (4.2.6) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
activesupport (4.2.6) lib/active_support/callbacks.rb:778:in`_run_perform_callbacks'
activesupport (4.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
activejob (4.2.6) lib/active_job/execution.rb:31:in`perform_now'
activejob (4.2.6) lib/active_job/execution.rb:21:in `execute'
activejob (4.2.6) lib/active_job/queue_adapters/inline_adapter.rb:14:in`enqueue'
activejob (4.2.6) lib/active_job/enqueuing.rb:71:in `block in enqueue'
activesupport (4.2.6) lib/active_support/callbacks.rb:117:in`call'
activesupport (4.2.6) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
activesupport (4.2.6) lib/active_support/callbacks.rb:505:in`call'
activesupport (4.2.6) lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
activesupport (4.2.6) lib/active_support/callbacks.rb:343:in`block (2 levels) in simple'
activejob (4.2.6) lib/active_job/logging.rb:14:in `block (3 levels) in <module:Logging>'
activejob (4.2.6) lib/active_job/logging.rb:43:in`block in tag_logger'
activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.6) lib/active_support/tagged_logging.rb:26:in`tagged'
activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `tagged'
activejob (4.2.6) lib/active_job/logging.rb:43:in`tag_logger'
activejob (4.2.6) lib/active_job/logging.rb:13:in `block (2 levels) in <module:Logging>'
activesupport (4.2.6) lib/active_support/callbacks.rb:441:in`instance_exec'
activesupport (4.2.6) lib/active_support/callbacks.rb:441:in `block in make_lambda'
activesupport (4.2.6) lib/active_support/callbacks.rb:342:in`block in simple'
activesupport (4.2.6) lib/active_support/callbacks.rb:497:in `block in around'
activesupport (4.2.6) lib/active_support/callbacks.rb:505:in`call'
activesupport (4.2.6) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_enqueue_callbacks'
activesupport (4.2.6) lib/active_support/callbacks.rb:81:in`run_callbacks'
activejob (4.2.6) lib/active_job/enqueuing.rb:67:in `enqueue'
activejob (4.2.6) lib/active_job/enqueuing.rb:17:in`perform_later'
curation_concerns (1.3.0) app/actors/curation_concerns/actors/file_actor.rb:25:in `ingest_file'
curation_concerns (1.3.0) app/actors/curation_concerns/actors/file_set_actor.rb:45:in`create_content'
curation_concerns (1.3.0) app/actors/curation_concerns/actors/attach_files_actor.rb:28:in `attach_file'
curation_concerns (1.3.0) app/actors/curation_concerns/actors/attach_files_actor.rb:20:in`block in attach_files'
curation_concerns (1.3.0) app/actors/curation_concerns/actors/attach_files_actor.rb:19:in `each'
curation_concerns (1.3.0) app/actors/curation_concerns/actors/attach_files_actor.rb:19:in`all?'
curation_concerns (1.3.0) app/actors/curation_concerns/actors/attach_files_actor.rb:19:in `attach_files'
curation_concerns (1.3.0) app/actors/curation_concerns/actors/attach_files_actor.rb:6:in`create'
curation_concerns (1.3.0) app/actors/curation_concerns/actors/actor_stack.rb:21:in `create'
curation_concerns (1.3.0) app/actors/curation_concerns/actors/assign_representative_actor.rb:5:in`create'
curation_concerns (1.3.0) app/actors/curation_concerns/actors/actor_stack.rb:21:in `create'
curation_concerns (1.3.0) app/actors/curation_concerns/actors/add_to_work_actor.rb:6:in`create'
curation_concerns (1.3.0) app/actors/curation_concerns/actors/actor_stack.rb:21:in `create'
curation_concerns (1.3.0) app/actors/curation_concerns/actors/add_to_collection_actor.rb:6:in`create'
curation_concerns (1.3.0) app/actors/curation_concerns/actors/actor_stack.rb:21:in `create'
curation_concerns (1.3.0) app/controllers/concerns/curation_concerns/curation_concern_controller.rb:38:in`create'
actionpack (4.2.6) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.2.6) lib/abstract_controller/base.rb:198:in`process_action'
actionpack (4.2.6) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.6) lib/abstract_controller/callbacks.rb:20:in`block in process_action'
activesupport (4.2.6) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.6) lib/active_support/callbacks.rb:555:in`block (2 levels) in compile'
activesupport (4.2.6) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.6) lib/active_support/callbacks.rb:92:in`**run_callbacks**'
activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
activesupport (4.2.6) lib/active_support/callbacks.rb:81:in`run_callbacks'
actionpack (4.2.6) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.6) lib/action_controller/metal/rescue.rb:29:in`process_action'
actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.6) lib/active_support/notifications.rb:164:in`block in instrument'
activesupport (4.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.6) lib/active_support/notifications.rb:164:in`instrument'
actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.6) lib/action_controller/metal/params_wrapper.rb:250:in`process_action'
activerecord (4.2.6) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.6) lib/abstract_controller/base.rb:137:in`process'
actionview (4.2.6) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.6) lib/action_controller/metal.rb:196:in`dispatch'
actionpack (4.2.6) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.6) lib/action_controller/metal.rb:237:in`block in action'
actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:43:in`serve'
actionpack (4.2.6) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.6) lib/action_dispatch/journey/router.rb:30:in`each'
actionpack (4.2.6) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:817:in`call'
warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
warden (1.2.6) lib/warden/manager.rb:34:in`catch'
warden (1.2.6) lib/warden/manager.rb:34:in `call'
rack (1.6.4) lib/rack/etag.rb:24:in`call'
rack (1.6.4) lib/rack/conditionalget.rb:38:in `call'
rack (1.6.4) lib/rack/head.rb:13:in`call'
actionpack (4.2.6) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/flash.rb:260:in`call'
rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.4) lib/rack/session/abstract/id.rb:220:in`call'
actionpack (4.2.6) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.6) lib/active_record/query_cache.rb:36:in`call'
activerecord (4.2.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
active-fedora (10.0.0) lib/active_fedora/ldp_cache.rb:26:in`call'
activerecord (4.2.6) lib/active_record/migration.rb:377:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/callbacks.rb:29:in`block in call'
activesupport (4.2.6) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
activesupport (4.2.6) lib/active_support/callbacks.rb:778:in`_run_call_callbacks'
activesupport (4.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.6) lib/action_dispatch/middleware/callbacks.rb:27:in`call'
actionpack (4.2.6) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/remote_ip.rb:78:in`call'
actionpack (4.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
web-console (2.3.0) lib/web_console/middleware.rb:20:in`block in call'
web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
web-console (2.3.0) lib/web_console/middleware.rb:18:in`call'
actionpack (4.2.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.6) lib/rails/rack/logger.rb:38:in`call_app'
railties (4.2.6) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in`block in tagged'
activesupport (4.2.6) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in`tagged'
railties (4.2.6) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.6) lib/action_dispatch/middleware/request_id.rb:21:in`call'
rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.4) lib/rack/runtime.rb:18:in`call'
activesupport (4.2.6) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in`call'
actionpack (4.2.6) lib/action_dispatch/middleware/static.rb:120:in `call'
rack (1.6.4) lib/rack/sendfile.rb:113:in`call'
railties (4.2.6) lib/rails/engine.rb:518:in `call'
railties (4.2.6) lib/rails/application.rb:165:in`call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
rack (1.6.4) lib/rack/content_length.rb:15:in`call'
rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
/usr/local/lib/ruby/2.3.0/webrick/httpserver.rb:140:in`service'
/usr/local/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
/usr/local/lib/ruby/2.3.0/webrick/server.rb:296:in`block in start_thread'
Request

Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"brBV3fSFLv+gI+FtK6K+FoXnPIYKAuRAyzFRyPhOhHN3P/wCGXTm+ZB/PlR2ydjCXg9DZz0KND1/8eU2EFT+fg==",
 "work"=>{"title"=>["Hurricane Matthew - New Providence,
 The Bahamas Flood Boundary Assessment"],
 "creator"=>["Pacific Data Center"],
 "contributor"=>[""],
 "description"=>[""],
 "subject"=>[""],
 "publisher"=>[""],
 "source"=>[""],
 "language"=>[""],
 "files"=>[#<ActionDispatch::Http::UploadedFile:0x007f5ddb15f820 @tempfile=#<Tempfile:/tmp/RackMultipart20161016-1-8li4c0.pdf>,
 @original_filename="PDC_TC_Matthew_Flood_Boundary_Assessment_Bahamas.pdf",
 @content_type="application/pdf",
 @headers="Content-Disposition: form-data; name=\"work[files][]\"; filename=\"PDC_TC_Matthew_Flood_Boundary_Assessment_Bahamas.pdf\"\r\nContent-Type: application/pdf\r\n">],
 "visibility_during_embargo"=>"restricted",
 "embargo_release_date"=>"2016-10-17",
 "visibility_after_embargo"=>"open",
 "visibility_during_lease"=>"open",
 "lease_expiration_date"=>"2016-10-17",
 "visibility_after_lease"=>"restricted",
 "visibility"=>"restricted",
 "rights"=>["http://creativecommons.org/publicdomain/mark/1.0/",
 ""]},
 "commit"=>"Create Work"}

**Comment by electrickite** [comment]
It looks like Image Magick can't validate the PDF. Would you be able to attach the file you're trying to upload to this issue?

**Comment by spikewilliams** [comment]
File is attached.

[PDC_TC_Matthew_Flood_Boundary_Assessment_Bahamas.pdf](https://github.com/osulibraries/hydra-docker-demo/files/531929/PDC_TC_Matthew_Flood_Boundary_Assessment_Bahamas.pdf)

**Comment by electrickite** [comment]
Thanks @spikewilliams! The docker image for the Rails app was missing ghostscript, causing the ImageMagick `identify` command to fail for PDF files. 7afe4d6e26bc78fa8caf16d8650271e51fe89490 should resolve the issue.

You'll need to run `docker-compose build app` to re-build the image.
